version: '3'

services:

  postgis:
    image: postgis/postgis:${POSTGIS_VERSION}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    env_file:
      - compose-postgis.env
      - compose-postgis.env.local
    ports:
      - 5432:5432
    networks:
      - svcnet

volumes:

  postgis-data:
    driver: local
