version: "3"

networks:
  svcnet:
    external: true

services:
  unleash:
    image: unleashorg/unleash-server:6.5.3
    volumes:
      - unleash-6.5.3-data:/data
      - ./unleash/config:/app/config
    env_file:
      - composer-unleash.env
      - composer-unleash.env.local
    ports:
      - 4242:4242
    networks:
      - svcnet

volumes:
  unleash-6.5.3-data:
    driver: local
